### ISSUE TITLE
panic: context deadline exceeded

### ISSUE THREAD

**Issue by Menziess** [stillmatic/gpt-cli#2]
I'm receiving this error while ChatGPT is writing out the response in the terminal:

```
goroutine 1 [running]:
main.main()
	/home/<name>/go/pkg/mod/github.com/stillmatic/chat@v0.2.2/main.go:136 +0x1c5
```

**Comment by rfahmi** [comment]
same here

**Comment by TechDufus** [comment]
If you both (@rfahmi @Menziess) want to pull my forked branch and build / test locally to see if #3 resolves this for you, you can..

**Comment by Menziess** [comment]
The issue seems to be resolved.

**Comment by stillmatic** [comment]
The original motivation was that the API server was quite unreliable and failing to connect; 20 seconds was probably too long (especially for long responses) but some window is helpful. It's probably better to cancel it based on _when the first byte arrives_ to the stream (i.e. give 2 seconds for the API to respond, otherwise cancel). That was quite tricky to get right unfortunately.

It's removed now, thanks for the fix!

**Comment by TechDufus** [comment]
Going to resurrect this.... 

```error
panic: context deadline exceeded (Client.Timeout or context cancellation while reading body)

goroutine 1 [running]:
main.main()
        /home/techdufus/go/pkg/mod/github.com/stillmatic/chat@v0.2.3/main.go:133 +0x1c5
```

The chat session lasted much longer thanks to [v0.2.3](https://github.com/stillmatic/chat/releases/tag/v0.2.3) but still isn't completely resolved it seems?
